name: Continuous Integration/Deployment

on: [push]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGION: ${{ secrets.REGION }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Debug Environment Variables
        run: |
          echo "Registry Name: $REGISTRY_NAME"
          echo "Region: $REGION"
          echo "Project ID: $PROJECT_ID"
          echo "Service Name: $SERVICE_NAME"
          echo "Service Account Key: $SERVICE_ACCOUNT_KEY"
          echo "Repo Name: $REPO_NAME"
      
      - name: Set up Python environment
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install dvc[gs]
          export GOOGLE_APPLICATION_CREDENTIALS=$SERVICE_ACCOUNT_KEY

      - name: Set up GCLOUD SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      
      - name: Build Docker image
        run: |
          docker build -t netapi .
          docker images  # Agregar este comando para listar imágenes

      - name: Configure Docker for Google Artifact Registry
        run: echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag netapi us-central1-docker.pkg.dev/netsquared-407819/net-deploy/netapiv1

      - name: Push Docker image to - Google Artifact Registry
        run: docker push us-central1-docker.pkg.dev/netsquared-407819/net-deploy/netapiv1

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME --region=$REGION --image=us-central1-docker.pkg.dev/netsquared-407819/net-deploy/netapiv1

