name: Continuous Integration/Deployment

on: [push]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGION: ${{ secrets.REGION }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Debug Environment Variables
        run: |
          echo "Registry Name: $REGISTRY_NAME"
          echo "Region: $REGION"
          echo "Project ID: $PROJECT_ID"
          echo "Service Name: $SERVICE_NAME"
          echo "Service Account Key: $SERVICE_ACCOUNT_KEY"
          echo "Repo Name: $REPO_NAME"
      
      - name: Set up Python environment
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install dvc[gs]
          export GOOGLE_APPLICATION_CREDENTIALS=$SERVICE_ACCOUNT_KEY

      - name: Set up GCLOUD SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker
      
      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REGISTRY_NAME:$GITHUB_SHA .
          docker images  # Agregar este comando para listar imágenes

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REGISTRY_NAME:$GITHUB_SHA .

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update $SERVICE_NAME --region=$REGION --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REGISTRY_NAME:$GITHUB_SHA

